# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField(max_length=200)),
                ('document', models.FileField(upload_to='document')),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronic and Communincation'), ('EEE', 'Electrical and Electronic Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], default='CSE', max_length=200)),
                ('visibilty', models.CharField(choices=[('pr', 'PRIVATE'), ('pu', 'PUBLIC')], default='pu', max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Author')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='documents',
            name='key',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.KeyWord'),
        ),
    ]
