# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='branch',
            field=models.CharField(choices=[('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electronic and Communincation', 'Electronic and Communincation'), ('Electrical and Electronic Engineering', 'Electrical and Electronic Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering')], default='Computer Science and Engineering', max_length=200),
        ),
        migrations.AlterField(
            model_name='documents',
            name='visibilty',
            field=models.CharField(choices=[('PRIVATE', 'PRIVATE'), ('PUBLIC', 'PUBLIC')], default='PUBLIC', max_length=200),
        ),
    ]
