# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171103_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
