# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_documents_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
    ]
