# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20171105_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
